# Generated by Django 4.1.2 on 2022-10-25 04:29

from django.db import migrations, models
import django.db.models.deletion
import django_sequence.fields


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.product')),
                ('sequence', django_sequence.fields.SequenceField(blank=True, default=django_sequence.fields.get_sequence_object, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sequence.sequence')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
