# Generated by Django 4.1.2 on 2022-10-25 19:25

from django.db import migrations, models
import django.db.models.deletion
import django_sequence.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='human readable representation of value', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, help_text='description of this entry', max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False, help_text='set to true when all stages have a state of completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='short reference for stage', max_length=64)),
                ('description', models.CharField(blank=True, help_text='detailed description of stage', max_length=255, null=True)),
                ('order', models.IntegerField(help_text='operational order of stage (where 1 is the first)')),
                ('details', models.CharField(blank=True, help_text='additional details, such as incomplete reason', max_length=255, null=True)),
                ('blocking', models.BooleanField(default=True, help_text='if True, do not continue to next stage if a failure or error occurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(default=django_sequence.models.get_default_result, help_text='outcome of model_sequence stage', on_delete=django.db.models.deletion.CASCADE, to='django_sequence.result')),
                ('sequence', models.ForeignKey(help_text='model_sequence this stage belongs to', on_delete=django.db.models.deletion.CASCADE, to='django_sequence.sequence')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='human readable representation of value', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, help_text='description of this entry', max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_stage', to='django_sequence.stage')),
                ('to_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_stage', to='django_sequence.stage')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='state',
            field=models.ForeignKey(default=django_sequence.models.get_default_state, help_text='current activity of model_sequence stage', on_delete=django.db.models.deletion.CASCADE, to='django_sequence.state'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='transitions',
            field=models.ManyToManyField(to='django_sequence.transition'),
        ),
    ]
