# Generated by Django 4.1.2 on 2022-10-25 00:19

from django.db import migrations

def populate_states(apps, schema_editor):
    """ populate State values """
    State = apps.get_model('django_sequence', 'State')
    data_list = [{'name': 'pending', 
                 'description': 'activity on this stage is expected but has not yet started'},
                 {'name': 'started', 
                 'description': 'activity on this stage has started'},
                 {'name': 'paused', 
                 'description': 'activity on this stage has started, but been purposely paused before completion'},
                 {'name': 'completed', 
                 'description': 'activity on this stage has completed'},
                 {'name': 'blocked', 
                 'description': 'activity on this stage is blocked by a previous stage'},
                 ]
    for data in data_list:
        State.objects.get_or_create(name=data['name'], defaults=data)


def populate_results(apps, schema_editor):
    """ populate Result values """
    Result = apps.get_model('django_sequence', 'Result')
    data_list = [{'name': 'success', 
                 'description': 'stage completed successfully with no issues'},
                 {'name': 'fail', 
                 'description': 'stage completed with a well-defined failure condition'},
                 {'name': 'error', 
                 'description': 'stage encountered an error and could not complete'},
                 {'name': 'unknown', 
                 'description': 'stage has not completed, or completion can not be determined'},
                 ]
    for data in data_list:
        Result.objects.get_or_create(name=data['name'], defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ('django_sequence', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_states),
        migrations.RunPython(populate_results),
    ]
